# Generated by Django 4.1 on 2022-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_user_delete_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="u_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
