# Generated by Django 4.1 on 2022-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_alter_user_u_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="u_avatar",
        ),
        migrations.AlterField(
            model_name="user",
            name="u_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="u_gender",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="u_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="u_name",
            field=models.CharField(default=123, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
