# Generated by Django 4.1 on 2022-12-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CircleOfPlan',
        ),
    ]
