# Generated by Django 4.0 on 2022-12-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comment', '0001_initial'),
        ('Plan', '0001_initial'),
        ('User', '0006_user_u_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.plan'),
        ),
        migrations.AddField(
            model_name='commentplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
