# Generated by Django 4.1.2 on 2022-10-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_password', models.CharField(max_length=20)),
                ('s_name', models.CharField(max_length=20, null=True)),
                ('s_dorm', models.CharField(max_length=30, null=True)),
                ('s_gender', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
