# Generated by Django 4.1 on 2022-12-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_remove_user_u_avatar_alter_user_u_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="u_id",
        ),
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
