# Generated by Django 4.1 on 2022-12-11 07:57

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_remove_user_u_id_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="u_avatar",
            field=models.FileField(
                default="avatar/default.png",
                null=True,
                upload_to=User.models.User.user_directory_path,
                verbose_name="头像",
            ),
        ),
    ]
