# Generated by Django 4.1.2 on 2022-10-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
                ('d_category', models.CharField(max_length=20, null=True)),
                ('d_cuisine', models.CharField(max_length=30, null=True)),
                ('d_calories', models.IntegerField()),
                ('d_price', models.IntegerField()),
            ],
        ),
    ]
