# Generated by Django 4.1 on 2022-12-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("u_id", models.IntegerField(primary_key=True, serialize=False)),
                ("u_password", models.CharField(max_length=20)),
                ("u_name", models.CharField(max_length=20, null=True, unique=True)),
                ("u_position", models.CharField(max_length=30, null=True)),
                ("u_gender", models.BooleanField()),
                ("u_email", models.EmailField(max_length=254)),
                ("u_age", models.IntegerField(null=True)),
                ("u_height", models.IntegerField(null=True)),
                ("u_weight", models.IntegerField(null=True)),
                (
                    "u_avatar",
                    models.FileField(
                        null=True, upload_to="uploads/", verbose_name="头像"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
