# Generated by Django 4.1 on 2022-12-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_password', models.CharField(max_length=20)),
                ('u_name', models.CharField(max_length=20, unique=True)),
                ('u_position', models.CharField(max_length=30, null=True)),
                ('u_gender', models.BooleanField(null=True)),
                ('u_email', models.EmailField(max_length=254, null=True)),
                ('u_age', models.IntegerField(null=True)),
                ('u_height', models.IntegerField(null=True)),
                ('u_weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
