# Generated by Django 4.1 on 2022-12-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExerArea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(max_length=20)),
                ('sp_content', models.CharField(max_length=20)),
                ('sp_difficulty', models.CharField(max_length=20)),
                ('sp_calories', models.IntegerField()),
                ('sp_time', models.IntegerField()),
                ('exerArea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExerArea.exerarea')),
            ],
        ),
    ]
